### ISSUE TITLE
Error on conversion to s3o, not present in prior version

### ISSUE THREAD

**Issue by TheSilverHornet** [beyond-all-reason/OBJ2S3O#2]
[corcrw.zip](https://github.com/beyond-all-reason/OBJ2S3O/files/13539840/corcrw.zip)

With this object in particular. Previous version of obj2s3o is completely fine

![image](https://github.com/beyond-all-reason/OBJ2S3O/assets/37483246/2906cbf3-a619-42ba-9042-e90fe6d51701)

Poke me on discord if you need any more info :)

**Comment by Beherith** [comment]
fixed
